'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан программой.
'     Исполняемая версия:4.0.30319.42000
'
'     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
'     повторной генерации кода.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace TranslatorService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://api.microsofttranslator.com/v1/soap.svc", ConfigurationName:="TranslatorService.LanguageService")>  _
    Public Interface LanguageService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://api.microsofttranslator.com/v1/soap.svc/LanguageService/GetLanguages", ReplyAction:="http://api.microsofttranslator.com/v1/soap.svc/LanguageService/GetLanguagesRespon"& _ 
            "se")>  _
        Function GetLanguages(ByVal appId As String) As String()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://api.microsofttranslator.com/v1/soap.svc/LanguageService/GetLanguageNames", ReplyAction:="http://api.microsofttranslator.com/v1/soap.svc/LanguageService/GetLanguageNamesRe"& _ 
            "sponse")>  _
        Function GetLanguageNames(ByVal appId As String, ByVal locale As String) As String()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://api.microsofttranslator.com/v1/soap.svc/LanguageService/Detect", ReplyAction:="http://api.microsofttranslator.com/v1/soap.svc/LanguageService/DetectResponse")>  _
        Function Detect(ByVal appId As String, ByVal text As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://api.microsofttranslator.com/v1/soap.svc/LanguageService/Translate", ReplyAction:="http://api.microsofttranslator.com/v1/soap.svc/LanguageService/TranslateResponse")>  _
        Function Translate(ByVal appId As String, ByVal text As String, ByVal from As String, ByVal [to] As String) As String
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface LanguageServiceChannel
        Inherits TranslatorService.LanguageService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class LanguageServiceClient
        Inherits System.ServiceModel.ClientBase(Of TranslatorService.LanguageService)
        Implements TranslatorService.LanguageService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetLanguages(ByVal appId As String) As String() Implements TranslatorService.LanguageService.GetLanguages
            Return MyBase.Channel.GetLanguages(appId)
        End Function
        
        Public Function GetLanguageNames(ByVal appId As String, ByVal locale As String) As String() Implements TranslatorService.LanguageService.GetLanguageNames
            Return MyBase.Channel.GetLanguageNames(appId, locale)
        End Function
        
        Public Function Detect(ByVal appId As String, ByVal text As String) As String Implements TranslatorService.LanguageService.Detect
            Return MyBase.Channel.Detect(appId, text)
        End Function
        
        Public Function Translate(ByVal appId As String, ByVal text As String, ByVal from As String, ByVal [to] As String) As String Implements TranslatorService.LanguageService.Translate
            Return MyBase.Channel.Translate(appId, text, from, [to])
        End Function
    End Class
End Namespace
